language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
    - SYMFONY_VERSION=^2.3.3
    - SYMFONY_VERSION=^2.8.0
    - SYMFONY_VERSION=^3.0

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/framework-bundle:${SYMFONY_VERSION}" "symfony/console:${SYMFONY_VERSION}" --no-update; fi;
  - composer install

script: phpunit -v
