language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
    - SYMFONY_VERSION=^2.3.3
    - SYMFONY_VERSION=^2.8.0
    - SYMFONY_VERSION=^3.0

install:
  - composer require "symfony/framework-bundle:${SYMFONY_VERSION}" "symfony/console:${SYMFONY_VERSION}"

script: phpunit -v
